### PR TITLE
011 bug fix quiz previous button and score quizzes

### LINKED ISSUE #17: Fix quiz scoring
Only the last quiz answered can get a score.

### LINKED ISSUE #18: Fix previous button when users answer quizzes
When the previous button is pressed a new answer instance is created and on the review page, both the old and new answer instances are shown.

### PR DESCRIPTION
**Pull request by BaiasPaul**
fix quiz previous button and score quizzes

### CODE REVIEW

File: config/config.php [hunk 1]
```diff
@@ -305,13 +315,13 @@
                 Router::CONFIG_KEY_ATTRIBUTES => []
             ],
```
Comment (victortodoran) [inline config/config.php:317]: We do not leave commented code in our merge requests.

File: public/index.php [hunk 2]
```diff
@@ -24,6 +24,6 @@
 } catch (RouteNotFoundException $e){
     $body = Stream::createFromString("");
     $responseWithoutHeader = new Response($body, '1.1', 301);
```
Comment (victortodoran) [inline public/index.php:26]: Change has nothing to do with commit|PR message.

File: src/Controller/AuthController.php [hunk 3]
```diff
@@ -71,14 +70,10 @@ public function login(Request $request)
             //the messageManager holds all the errorMessages that will be displayed in the view
             $this->messageManager->addErrorMessage($e->getMessage());
```
Comment (victortodoran) [inline src/Controller/AuthController.php:72]: Change has nothing to do with commit|PR message.
Compare PR name with method/Controller name

File: src/Controller/AuthController.php [hunk 4]
```diff
@@ -71,14 +70,10 @@ public function login(Request $request)
...
 
-            return $response->withHeader('Location', $location);
-        }
-        $location .= strtolower($user->getRole());
-        if ($user->getRole() === 'candidate'){
-            $location .= '?page=1';
+            return $response->withHeader('Location', "/");
         }
```
Comment (victortodoran) [inline src/Controller/AuthController.php:75]: Analog

File: src/Controller/AuthController.php [hunk 5]
```diff
@@ -90,7 +85,7 @@ public function logout()
         $body = Stream::createFromString("");
         $response = new Response($body, '1.1', '301');
```
Comment (victortodoran) [inline src/Controller/AuthController.php:87]: Analog

File: src/Controller/QuestionInstanceController.php [hunk 6]
```diff
@@ -30,44 +30,45 @@ public function __construct(RendererInterface $renderer, QuestionInstanceService
     public function saveAnswer(Request $request, array $requestAttributes)
     {
         $answer = $request->getParameter('answer');
-        $this->questionInstanceService->saveAnswer($answer,$requestAttributes['id']);
+        $this->questionInstanceService->saveAnswer($answer, $requestAttributes['id']);
         $questionNumber = $request->getParameter('question');
         $body = Stream::createFromString("");
         $response = new Response($body, '1.1', 301);
```
Comment (victortodoran) [inline src/Controller/QuestionInstanceController.php:37]: Analog

File: src/Controller/QuestionInstanceController.php [hunk 7]
```diff
@@ -30,44 +30,45 @@ public function __construct(RendererInterface $renderer, QuestionInstanceService
...
-        return $response->withHeader('Location', 'http://quizApp.com/candidate-quiz-page?question='.($questionNumber+1));
+        return $response->withHeader('Location', '/candidate-quiz-page?question=' . ($questionNumber + 1));
     }
 
     public function back(Request $request, array $requestAttributes)
     {
         $questionNumber = $request->getParameter('question');
         $body = Stream::createFromString("");
-        $response = new Response($body, '1.1', '301');
+        $response = new Response($body, '1.1', 301);
```
Comment (victortodoran) [inline src/Controller/QuestionInstanceController.php:46]: Analog

File: src/Controller/QuestionInstanceController.php [hunk 8]
```diff
@@ -30,44 +30,45 @@ public function __construct(RendererInterface $renderer, QuestionInstanceService
...
     }
 
     public function save(Request $request, array $requestAttributes)
     {
         $answer = $request->getParameter('answer');
-        $this->questionInstanceService->saveAnswer($answer,$requestAttributes['id']);
+        $this->questionInstanceService->saveAnswer($answer, $requestAttributes['id']);
         $body = Stream::createFromString("");
-        $response = new Response($body, '1.1', '301');
+        $response = new Response($body, '1.1', 301);
```
Comment (victortodoran) [inline src/Controller/QuestionInstanceController.php:56]: Analog

File: src/Controller/QuestionTemplateController.php [hunk 9]
```diff
@@ -52,7 +52,7 @@ public function createQuestion(Request $request)
         $body = Stream::createFromString("");
         $response = new Response($body, '1.1', 301);
```
Comment (victortodoran) [inline src/Controller/QuestionTemplateController.php:54]: Analog

File: src/Controller/QuestionTemplateController.php [hunk 10]
```diff
@@ -100,7 +100,7 @@ public function editQuestion(Request $request, array $requestAttributes)
...
```
Comment (victortodoran) [inline src/Controller/QuestionTemplateController.php:102]: Analog

File: src/Controller/QuizInstanceController.php [hunk 11]
```diff
@@ -33,18 +34,17 @@ public function __construct(RendererInterface $renderer, QuizInstanceService $qu
 
     public function showCandidateQuizzes(Request $request, array $requestAttributes)
     {
```
Comment (victortodoran) [inline src/Controller/QuizInstanceController.php:36]: If you need the Session in the Controller inject it. (Consider using a wrapper over the session for Authentication). Services should expose their properties through getters and the Controller should not know that the service has a Session object. IMO you broke encapsulation.

File: src/Controller/QuizInstanceController.php [hunk 12]
```diff
@@ -33,18 +34,17 @@ public function __construct(RendererInterface $renderer, QuizInstanceService $qu
...
+        $redirectToLogin = $this->verifySessionUserName($this->quizInstanceService->getSession());
+        if ($redirectToLogin) {
+            return $redirectToLogin;
+        }
```
Comment (victortodoran) [inline src/Controller/QuizInstanceController.php:40]: It's smelly that this service has such a function `getFromParameter()`. Also why cast the return of the method each time is called. Why not cast the result inside the method that computes it? When you have 4 arguments to a method out of which 3 are scalars and one is an array you should consider it a red flag and return to OOP.

File: src/Controller/QuizInstanceController.php [hunk 13]
```diff
@@ -57,7 +57,7 @@ public function showCandidateQuizListing(Request $request, array $requestAttribu
         $body = Stream::createFromString("");
         $response = new Response($body, '1.1', 301);
```
Comment (victortodoran) [inline src/Controller/QuizInstanceController.php:59]: Analog. Has nothing to do with PR

File: src/Controller/QuizTemplateController.php [hunk 14]
```diff
@@ -4,17 +4,30 @@
```
Comment (victortodoran) [inline src/Controller/QuizTemplateController.php:4]: This refactor could've been implemented in a separate PR. It's been a while and I'm unsure if I reached the code that corresponds to this PR/ticket.

File: src/Controller/ResultController.php [hunk 15]
```diff
@@ -43,26 +44,19 @@ public function __construct(RendererInterface $renderer, ResultService $resultSe
      * @param array $requestAttributes
      * @return Message|MessageInterface
      */
-    public function showResults(Request $request, array $requestAttributes)
+    public function showResults(Request $request, array $requestAttributes): MessageInterface
     {
         $redirectToLogin = $this->verifySessionUserName($this->resultService->getSession());
```
Comment (victortodoran) [inline src/Controller/ResultController.php:49]: Consider extracting authorization to a higher level. In the dispatcher for example.  There is an approach in the document provided by Andra a few weeks ago.

File: src/Controller/ResultController.php [hunk 16]
```diff
@@ -75,13 +69,14 @@ public function showResults(Request $request, array $requestAttributes)
      * @param array $requestAttributes
      * @return Response
      */
```
Comment (victortodoran) [inline src/Controller/ResultController.php:71]: Function name does not match logic.
Logic tells me you load the results for a single quiz.
The name tells me you show the results for multiple quizzes.
Please fix this. 
Please also add space before and after operators.  `'key'=>$var`   will look like this `'key' => $var`

File: src/Controller/UserController.php [hunk 17]
```diff
@@ -105,7 +105,7 @@ public function createUser(Request $request)
         $body = Stream::createFromString("");
```
Comment (victortodoran) [inline src/Controller/UserController.php:105]: All these changes could've been in a different PR.

File: src/Entity/QuizInstance.php [hunk 18]
```diff
@@ -94,7 +92,7 @@ public function getIsSaved()
     }
 
     /**
-     * @param int $isSaved
+     * @param int
      */
```
Comment (victortodoran) [inline src/Entity/QuizInstance.php:96]: strong type this param if possible.

File: src/Service/AbstractService.php [hunk 19]
```diff
@@ -92,7 +92,7 @@ public function getEntitiesByField($class, $fields, $currentPage, $resultsPerPag
     /**
      * @return SessionInterface
      */
```
Comment (victortodoran) [inline src/Service/AbstractService.php:94]: Services must not expose class attributes through getters. IMO you broke encapsulation.

File: src/Service/AppMessageManager.php [hunk 20]
```diff
@@ -58,6 +58,9 @@ public function getErrorMessages(): array
      */
```
Comment (victortodoran) [inline src/Service/AppMessageManager.php]: Good, yet it has nothing to do with PR/Issue

File: src/Service/ResultService.php [hunk 21]
```diff
@@ -35,10 +35,11 @@ public function getQuestionsAnswered($id)
      * Will be moved in another issue
      *
      * @param $score
+     * @param $quizId
      */
```
Comment (victortodoran) [inline src/Service/ResultService.php:39]: You should use more strong types in ur app.

File: src/Util/Paginator.php [hunk 22]
```diff
@@ -120,7 +120,7 @@ public function getPreviousPage()
      */
```
Comment (victortodoran) [inline src/Util/Paginator.php:120]: strong return type
